---

# To configure services, use full class/interface name as key
# Configure Logger (Monolog)
Psr\Log\LoggerInterface:
  name: 'app.log'
  path: 'logs'
  level: debug
  maxFiles: 7
  logServerEnabled: false
  logServerLevel: info
  logServerHost: localhost
  logServerPort: 1337

GuzzleHttp\Client:
  verify: false
  timeout: 60

App\SpaceTraders\ApiService:
  url: 'https://api.spacetraders.io/v2'
  headers:
    Accept: 'application/json'
    Content-Type: 'application/json'
  authHeader: 'Bearer %s'

App\Persistence\EntityManagerFactory:
  foo: bar